### ISSUE TITLE
colorout package interferes with pkg output, causes missing line breaks

### ISSUE THREAD

**Issue by slowkow** [jalvesaq/colorout#24] opened 2019-01-23 14:56 UTC
[colorout] is interfering with the output from [pkg], so line breaks are not appearing as they should.

[pkg]: https://github.com/r-lib/pkg
[colorout]: https://github.com/jalvesaq/colorout
[crayon]: https://github.com/r-lib/crayon

I think I should stop using colorout now that [crayon] is gaining more usage.

With `library(colorout)` in my `~/.Rprofile`:

```
Loading required package: colorout
> pkg::pkg_install("AnnotationDbi")
ℹ Checking for package metadata updates
✔ All 10 metadata files are current.

ℹ Loading session disk cached package metadata✔ Loading session disk cached package metadata✔ Using cached package metadata
Found  20  deps for  1/1  pkgs [⠙] Checking installed packagesFound  20  deps for  1/1  pkgs [⠹] Checking installed packagesFound  43  deps for  1/1  pkgs [⠸] Resolving standard (CRAN/BioC) packagesFound  43  deps for  1/1  pkgs [⠼] Resolving standard (CRAN/BioC) packages✔ 1 + 16 pkgs | kept 17, updated 0, new 0 | downloaded 0 (0 B) [4.4s]
```

Without colorout:

```
> pkg::pkg_install("AnnotationDbi")
ℹ Checking for package metadata updates
✔ All 10 metadata files are current.
✔ Loading session disk cached package metadata
✔ Using cached package metadata
✔ 1 + 16 pkgs | kept 17, updated 0, new 0 | downloaded 0 (0 B) [4.6s]
```

# Details

iTerm2 Build 3.2.7

```
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 3.5.1 (2018-07-02)
 os       macOS High Sierra 10.13.6
 system   x86_64, darwin15.6.0
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/New_York
 date     2019-01-23

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version    date       lib source
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)
 backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.0)
 callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.0)
 cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)
 colorout    * 1.2-0      2019-01-01 [1] local
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)
 curl          3.3        2019-01-10 [1] CRAN (R 3.5.2)
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.0)
 devtools    * 2.0.1      2018-10-26 [1] CRAN (R 3.5.1)
 digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)
 filelock      1.0.2      2018-10-05 [1] CRAN (R 3.5.0)
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.0)
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)
 memoise       1.1.0.9000 2019-01-18 [1] Github (hadley/memoise@1650ad7)
 pkg         * 0.1.1.9000 2019-01-23 [1] Github (r-lib/pkg@582d0d5)
 pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.0)
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.0)
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.0)
 processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.0)
 ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.0)
 R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.0)
 Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.0)
 remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.0)
 rlang         0.3.1.9000 2019-01-23 [1] Github (r-lib/rlang@02bff45)
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.0)
 testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.0)
 usethis     * 1.4.0      2018-08-14 [1] CRAN (R 3.5.0)
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.0)

[1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
```

**Comment by jalvesaq** [comment] 2019-01-23 15:23
Colorout already checks whether the string is colorized by another package:
https://github.com/jalvesaq/colorout/blob/master/src/colorout.c#L254

But it seems that R's output does not come in a single string. R breaks it in many pieces, and an ANSI color code might have been output in a previous string and still be active. So, I will not be surprised if colorout interferes in the colorizing made by other packages, but it should not mess with line breaks.

Perhaps the problem is here:
https://github.com/jalvesaq/colorout/blob/master/src/colorout.c#L261

**Comment by mo0zi** [comment] 2019-01-31 12:43
Is there a way to set a hook to temporarily detach the `colorout` package before a specific funcion call and, after successfull execution of the function, load the package again?

I am thinking of something like
```
# detach the colorout package _before_ the problematic function call
setHook(functionEvent(functionName="devtools::install_github", event="before.Run"),
               value=detach(package:colorout, detach=T))
# reload the colorout package _after_ the problematic function call
setHook(functionEvent(functionName="devtools::install_github", event="after.Run"),
               value=library(colorout))
```

Maybe this would be a workaround? However, I was not able to build a hook like this :/
Greetings

**Comment by jalvesaq** [comment] 2019-01-31 14:40
You may call the function `noColorOut()` to disable the colorizing of R output, and `ColorOut()` to enable it again. This will be faster than detaching colorout and attaching it again.

**Comment by mo0zi** [comment] 2019-02-01 07:41
Good point ty!

**Comment by jalvesaq** [comment] 2024-08-25 15:28
I guess this bug is finally fixed on the branch `fix_nl`.

When the output already had colors, it was always printed on `stdout`.

**Closed** 2024-08-26 19:55 UTC
